project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-on Exercise 0"
          href: Hands-on_Exe/Hands-on_Ex_00.html
        - text: "Hands-on Exercise 1"
          href: Hands-on_Exe/Hands-on_Ex_01.html
        - text: "Hands-on Exercise 2"
          href: Hands-on_Exe/Hands-on_Ex_02.html
        - text: "Hands-on Exercise 3"
          href: Hands-on_Exe/Hands-on_Ex_03.html
        - text: "Hands-on Exercise 4"
          href: Hands-on_Exe/Hands-on_Ex_04.html
        - text: "Hands-on Exercise 5"
          href: Hands-on_Exe/Hands-on_Ex_05.html
        - text: "Hands-on Exercise 7"
          href: Hands-on_Exe/Hands-on_Ex_07.html
        - text: "Hands-on Exercise 8"
          href: Hands-on_Exe/Hands-on_Ex_08qmd.html
        - text: "Hands-on Exercise 8_tmap 4.0"
          href: Hands-on_Exe/Hands-on_Ex_08_newTmap.html
        - text: "Hands-on Exercise 9"
          href: Hands-on_Exe/Hands-on_Ex_09.html
        - text: "Hands-on Exercise 10"
          href: Hands-on_Exe/Hands-on_Ex_10.html
          
          
      - text: "In-class Exercise"
        menu:
        - text: "In-class Exercise 4"
          href: In-class_Exe/In-class_Ex04.html
        - text: "In-class Exercise 5"
          href: In-class_Exe/In-class_Ex05.html
        - text: "In-class Exercise 7"
          href: In-class_Exe/In-class_Ex07.html
        
      - text: "Take-home Exercise"
        menu:
        - text: "Take-home Exercise 1"
          href: Take-home_Exe/Take-home_Ex_01.html
        - text: "Take-home Exercise 2"
          href: Take-home_Exe/Take-home_Ex_02.html
        - text: "Take-home Exercise 3"
          href: Take-home_Exe/Take-home_Ex_03.html
     
      - text: "Group 7 Project"
        href: "https://isss608jan25group7.netlify.app/"

      
    right:
      - href: index.qmd
        text: Home
     
      - about.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

