project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-on Exercise 0"
          href: Hands-on_Exe/Hands-on_Ex_00.html
          
      - text: "In-class Exercise"
        menu:
        - text: "In-class Exercise 1"
          href: In-class_Ex01.html
        
      - text: "Take-home Exercise"
        href: Take-home_ex.html
    
    right:
      - href: index.qmd
        text: Home
     
      - about.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

