---
title: "In-Class Exercise 09"
author: "Dew Stella Chan"
date-modified: "last-modified"
date: "2025-03-22"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(igraph, tidygraph, ggraph, 
               visNetwork, lubridate, clock,
               tidyverse, graphlayouts)
```


```{r}
GAStech_nodes <- read_csv("data/GAStech_email_node.csv")
GAStech_edges <- read_csv("data/GAStech_email_edge-v2.csv")
```

Important for the date and tijme to be in numerical fields

```{r}
glimpse(GAStech_edges)
```

This is the process the data to weekday field so that we can use a new column. 
```{r}
GAStech_edges <- GAStech_edges %>%
  mutate(SendDate = dmy(SentDate)) %>% #different field name to differentiate the two different sent date. 
  mutate(Weekday = wday(SentDate,
                        label = TRUE,
                        abbr = FALSE))
```


```{r}
GAStech_edges_aggregated <- GAStech_edges %>%
  filter(MainSubject == "Work related") %>%
  group_by(source, target, Weekday) %>%
    summarise(Weight = n()) %>%
  filter(source!=target) %>%
  filter(Weight > 1) %>%
  ungroup()
```
