---
title: "In-Class Ex 07"
author: "Dew Stella Chan"

date: "2025-03-01"
date-modified: "last-modified"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---


```{r}
pacman::p_load(tidyverse, tsibble, feasts, fable, seasonal)
```


```{r}
ts_data <- read_csv(
  "data/visitor_arrivals_by_air.csv")
```

```{r}
ts_data$`Month-Year` <- dmy(
  ts_data$`Month-Year`)
```

```{r}
ts_dataa_ts <- ts(ts_data) #indicate as time series data frame, is not tsclassibble dataframe
head (ts_data)
```


```{r}
ts_tsibble <- ts_data %>%
  mutate(Month = yearmonth(`Month-Year`)) %>%
  as_tsibble(index = `Month`)
```


```{r}
ts_longer <- ts_data %>%
  pivot_longer(cols = c(2:34),
               names_to = "Country",
               values_to = "Arrivals")


```


```{r}
ts_longer %>%
  filter(Country == "Vietnam") %>% #this could be one of the parameters. 
  ggplot(aes(x = `Month-Year`, 
             y = Arrivals))+
  geom_line(size = 0.5)
```
```{r}
ggplot(data = ts_longer, 
       aes(x = `Month-Year`, 
           y = Arrivals,
           color = Country))+
  geom_line(size = 0.5) +
  theme(legend.position = "bottom", 
        legend.box.spacing = unit(0.5, "cm"))
```

```{r}
#| echo: false
#| fig-height: 12 

ggplot(data = ts_longer, 
       aes(x = `Month-Year`, 
           y = Arrivals))+
  geom_line(size = 0.5) +
  facet_wrap(~ Country, #defination of rows is not required. due to the facet_wrap. 
             ncol = 3,
             scales = "free_y") + #y axis is not fixed. 
  theme_bw()
```

```{r}
tsibble_longer <- ts_tsibble %>%
  pivot_longer(cols = c(2:34),
               names_to = "Country",
               values_to = "Arrivals")
```


```{r}
tsibble_longer %>%
  filter(Country == "Italy" |
         Country == "Vietnam" |
         Country == "United Kingdom" |
         Country == "Germany") %>% 
  gg_season(Arrivals)
```
```{r}
tsibble_longer %>%
  filter(Country == "Vietnam" |
         Country == "Italy") %>% 
  autoplot(Arrivals) + 
  facet_grid(Country ~ ., scales = "free_y")
```

```{r}
#| fig-height: 6
tsibble_longer %>%
  filter(Country == "Vietnam" |
         Country == "Italy") %>% 
  gg_subseries(Arrivals) #the subseries function is a cycle plot
```
```{r}
tsibble_longer %>%
  filter(`Country` == "Vietnam") %>%
  ACF(Arrivals) %>% 
  autoplot()
```
```{r}
tsibble_longer %>%
  filter(`Country` == "Vietnam" |
         `Country` == "Italy" |
         `Country` == "United Kingdom" |
         `Country` == "China") %>%
  PACF(Arrivals) %>%
  autoplot()


```

