---
title: "In-class 05"
author: "Dew Stella Chan"
date: "2025-02-15"
date-modified: "last-modified"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---



```{r}
pacman::p_load(tidyverse, readxl, SmartEDA, easystats,gtsummary, ggstatsplot)
```

### Importing Data
```{r}
car_resale_org <-
  read_xls("data/In_Class_Ex05/ToyotaCorolla.xls", "data")
```

```{r}
summary(car_resale)
```

```{r}
summary(car_resale_org)
```

```{r}
list(car_resale)
```
```{r}
summary1  <- car_resale %>%
  ExpData(type=1)
```

making it into object class and further transform into a table in R

```{r}
car_resale %>% 
  ExpData(type=2)
```



```{r}
cols <- c("Mfg_Month","HP_Bin","CC_bin","Doors","Gears","Cylinders","Fuel_Type","Color","Met_Color","Automatic","Mfr_Guarantee","BOVAG_Guarantee","ABS","Airbag_1","Airbag_2","Airco","Automatic_airco","Boardcomputer","CD_Player","Central_Lock","Powered_Windows","Power_Steering","Radio","Mistlamps","Sport_Model","Backseat_Divider","Metallic_Rim","Radio_cassette","Tow_Bar")


car_resale <- read_xls ("data/In_Class_Ex05/ToyotaCorolla.xls",
                        sheet = "data") %>%
  mutate(Id = as.character(Id)) %>%
  mutate_each(funs(factor(.)),cols)
```
```{r}
car_resale %>%
  ExpNumViz(target=NULL,
            nlim=10,
            Page = c(2,2))

## page(2 2,) is to define the number of chart to be added in one plot. 
```
```{r}
car_resale %>%
  ExpNumViz(target = "Price",
            nlim=10,
            Page=c(2,2))
```
```{r}
#| fig-width: 12
#| fig-height: 10
car_resale %>%
  ExpCatViz(target =NULL,
            col="Sky blue",
            clim=10,
            margin=2,
            Page=c(4,4),
            sample=16)
```



```{r}
 model <- lm(Price ~ Age_08_04 + KM + Mfg_Year+
              Weight + Guarantee_Period, data = car_resale)
```



```{r}
check_c<-check_collinearity(model)
plot(check_c)
```

```{r}
 model1 <- lm(Price ~ Age_08_04 + KM + 
              Weight + Guarantee_Period, data = car_resale)
```


```{r}
check_normality(model1)
```

```{r}
#| fig-width: 12
#| fig-height: 10
check_model(model1)
```
we can use the checkc to plot it individually. 

for homogeneity of variance, we can see there are two set of data, we should build two model instead of 1 model. 

```{r}
summary(model1)
```
```{r}
tbl_regression(model1, intercept=TRUE)
```
```{r}
tbl_regression(model1, 
               intercept=TRUE) %>%
  add_glance_source_note(
    label=list(sigma~"\U03C3"),
    include = c(r.squared, adj.r.squared,
                AIC, statistic,
                p.value, sigma))
  
```

```{r}
p_model1<-parameters(model1)
```


```{r}
plot(parameters (model1))
```
```{r}
ggcoefstats(model1,
            output="plot")
```




