---
title: "Hands-on Ex 07"
author: "Dew Stella Chan"
date: "2025-02-23"
date-modified: "last-modified"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---

### Visualising and Analysing Time-oriented Data

```{r}
pacman::p_load(rootSolve, lmom, expm, Exact, gld, productplots, libcoin, inum, 
                 DescTools, ggmosaic, partykit, CGPfunctions, knitr, tidyverse,
               data.table, dplyr,ggthemes, readxl )
```

### Plotting Calender Heatmap

```{r}
attacks <- read.csv("data/eventlog.csv")
```

### Examining the data structure

```{r}
kable(head(attacks))
```

### Data Preparation

```{r}
make_hr_wkday <- function(ts, sc, tz) {
  real_times <- ymd_hms(ts, 
                        tz = tz[1], 
                        quiet = TRUE)
  dt <- data.table(source_country = sc,
                   wkday = weekdays(real_times),
                   hour = hour(real_times))
  return(dt)
  }

```

```{r}
wkday_levels <- c('Saturday', 'Friday', 
                  'Thursday', 'Wednesday', 
                  'Tuesday', 'Monday', 
                  'Sunday')

attacks <- attacks %>%
  group_by(tz) %>%
  do(make_hr_wkday(.$timestamp, 
                   .$source_country, 
                   .$tz)) %>% 
  ungroup() %>% 
  mutate(wkday = factor(
    wkday, levels = wkday_levels),
    hour  = factor(
      hour, levels = 0:23))
```

```{r}
grouped <- attacks %>% 
  count(wkday, hour) %>% 
  ungroup() %>%
  na.omit()

ggplot(grouped, 
       aes(hour, 
           wkday, 
           fill = n)) + 
geom_tile(color = "white", 
          size = 0.1) + 
theme_tufte(base_family = "Helvetica") + 
coord_equal() +
scale_fill_gradient(name = "# of attacks",
                    low = "sky blue", 
                    high = "dark blue") +
labs(x = NULL, 
     y = NULL, 
     title = "Attacks by weekday and time of day") +
theme(axis.ticks = element_blank(),
      plot.title = element_text(hjust = 0.5),
      legend.title = element_text(size = 8),
      legend.text = element_text(size = 6) )
```

### Building Multiple Calendar Heatmaps

#### Using different from code from prof kam

```{r}
top4 <- attacks %>%
  count(source_country, wkday, hour) %>%
  group_by(source_country) %>%
  summarise(total_attacks = sum(n)) %>%
  top_n(4, total_attacks) %>%
  arrange(desc(total_attacks))

grouped_top4 <- attacks %>%
  count(source_country, wkday, hour) %>% 
  ungroup() %>%
  na.omit() %>%
  semi_join(top4, by = "source_country")


```

```{r}
#| fig-width: 12 #to widen the space
#| fig-height: 12 #to lengthen the graph
#| 
ggplot(grouped_top4, 
       aes(hour, 
           wkday, 
           fill = n)) + 
geom_tile(color = "white", 
          size = 0.1) + 
theme_tufte(base_family = "Helvetica") + 
coord_equal() +
scale_fill_gradient(name = "# of attacks",
                    low = "sky blue", 
                    high = "dark blue") +
facet_wrap(~source_country)+
labs(x = NULL, 
     y = NULL, 
     title = "Attacks by weekday and time of day") +
theme(axis.ticks = element_blank(),
      axis.text.x = element_text(size = 7),
      plot.title = element_text(hjust = 0.5),
      legend.title = element_text(size = 8),
      legend.text = element_text(size = 6) ) 

```

### Plotting Cycle Plot

```{r}
air <- read_excel("data/arrivals_by_air.xlsx")
```

```{r}
air$month <- factor(month(air$`Month-Year`), 
                    levels=1:12, 
                    labels=month.abb, 
                    ordered=TRUE) 
air$year <- year(ymd(air$`Month-Year`))
```

```{r}
Vietnam <- air %>% 
  select(`Vietnam`, 
         month, 
         year) %>%
  filter(year >= 2010)
```

```{r}
hline.data <- Vietnam %>% 
  group_by(month) %>%
  summarise(avgvalue = mean(`Vietnam`))
```

```{r}
#| fig-width: 20 #to widen the space
#| fig-height: 8 #to lengthen the graph
ggplot() + 
  geom_line(data=Vietnam,
            aes(x=year, 
                y=`Vietnam`, 
                group=month), 
            colour="black") +
  geom_hline(aes(yintercept=avgvalue), 
             data=hline.data, 
             linetype=6, 
             colour="red", 
             size=0.5) + 
  facet_grid(~month) +
  labs(axis.text.x = element_blank(),
       title = "Visitor arrivals from Vietnam by air, Jan 2010-Dec 2019") +
  xlab("") +
  ylab("No. of Visitors") +
  theme_economist_white()

```

### Plotting Slopegraph

Step 1: Data Import

```{r}
rice <- read_csv("data/rice.csv")
```

```{r}
rice %>% 
  mutate(Year = factor(Year)) %>%
  filter(Year %in% c(1961, 1980)) %>%
  newggslopegraph(Year, Yield, Country,
                Title = "Rice Yield of Top 11 Asian Counties",
                SubTitle = "1961-1980",
                Caption = "Referred to codes by: Dr. Kam Tin Seong")
```
